image: ruby:3.2

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH

before_script:
    - apt-get update && apt-get install -y rsync
    - gem install bundler
    - bundle init
    - bundle add jekyll
    - bundle install
    - rsync -av .gitlab/ docs/

pages:
    stage: deploy
    script:
        - bundle exec jekyll build --destination public
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    environment: production

test:
    stage: test
    script:
        - bundle exec jekyll build --destination test
    artifacts:
        paths:
            - test
    rules:
        - if: $CI_COMMIT_BRANCH != "main"
