image: ruby:3.2

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH

before_script:
    - cd docs
    - gem install bundler
    - bundle init
    - bundle install

pages:
    stage: deploy
    script:
        - bundle exec jekyll build -d public
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    environment: production

test:
    stage: test
    script:
        - bundle exec jekyll build -d test
    artifacts:
        paths:
            - test
    rules:
        - if: $CI_COMMIT_BRANCH != "main"
