workflow:
    rules:
        - if: $CI_COMMIT_BRANCH

default:
    interruptible: true
    image: node:20

    before_script:
        - npm ci

pages:
    stage: deploy
    script:
        - npm run gitlab-actions --if-present
        - cp -r docs public
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    environment: production
