workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

default:
  interruptible: true
  image: node:20

  before_script:
    - apt-get update && apt-get install -y tree
    - npm ci

pages:
  stage: deploy
  script:
    - echo $TEST_VARIABLE
    - npm run gitlab-actions $TEAM_NUMBER $USERNAME $PASSWORD
    - mv docs public
    - tree public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
