name: Build static site

on:
    workflow_call:
        inputs:
            commitMessage:
                required: true
                type: string
    workflow_dispatch:
        inputs:
            commitMessage:
                description: 'Commit message for static site build'
                default: 'Manual build trigger'
                required: true
                type: string

concurrency:
    group: 'build-static-site'
    cancel-in-progress: true

permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Set environment variables
              id: set-vars
              run: |
                  COMMIT_MESSAGE="STATIC BUILD: ${{ github.event.head_commit.message || 'Automated build' }}"
                  BRANCH_NAME=$(echo "$COMMIT_MESSAGE" | tr -c '[:alnum:]_-' '-' | sed 's/-\{2,\}/-/g' | sed 's/^-//;s/-$//')
                  echo "::set-output name=COMMIT_MESSAGE::$COMMIT_MESSAGE"
                  echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
              shell: bash

            - name: Setup actions bot
              id: setup-actions-bot
              uses: devlooped/actions-bot@v1
              with:
                  name: static-site-builder[bot]
                  email: static-site-builder[bot]@users.noreply.github.com
                  gh_token: ${{ secrets.GH_TOKEN }}

            - uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build static site
              run: npm run prod-build --if-present

            - name: Run test
              run: npm test --if-present

            - name: Generate GitHub context JSON
              run: |
                  cd docs
                  echo '${{ toJson(github) }}' | jq '{job, ref, sha, repository, repository_Url, run_id, run_number, run_attempt, artifact_cache_size_limit, actor, trigerring_actor, workflow, event_name, event, ref_name, ref_protected, ref_type, secret_source, workflow_ref, workflow_sha, workspace}' | jq 'del(.event.base_ref, .event.organization, .event.repository, .event.sender)' > github-context.json
              shell: bash

            - name: Prettify all files
              run: npm run prettify --if-present

            - name: Commit and create pull request
              id: create-pull-request
              uses: peter-evans/create-pull-request@v6
              env:
                  BOT_AUTHOR: ${{ steps.setup-actions-bot.outputs.bot-author }}
                  COMMIT_MESSAGE: ${{ steps.set-vars.outputs.COMMIT_MESSAGE }}
                  BRANCH_NAME: ${{ steps.set-vars.outputs.BRANCH_NAME }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  commit-message: ${{ env.COMMIT_MESSAGE }}
                  committer: ${{ env.BOT_AUTHOR }}
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: ${{ env.BRANCH_NAME }}
                  title: ${{ env.COMMIT_MESSAGE }}
                  body: Automated build by ${{ env.BOT_AUTHOR }}

            - name: Merge pull request
              uses: juliangruber/merge-pull-request-action@v1
              env:
                  PULL_REQUEST_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
                  number: ${{ env.PULL_REQUEST_NUMBER }}
                  method: squash
