name: Build static site

on:
    workflow_call:
        inputs:
            commitMessage:
                required: true
                type: string
    workflow_dispatch:
        inputs:
            commitMessage:
                description: "Commit message for static site build"
                default: "Manual build trigger"
                required: true
                type: string

concurrency:
    group: "build-static-site"
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build static site
              run: npm run prod-build --if-present

            - name: Run test
              run: npm test --if-present

            - name: Generate GitHub context JSON
              run: |
                  cd docs
                  echo '${{ toJson(github) }}' | jq '{job, ref, sha, repository, repository_Url, run_id, run_number, run_attempt, artifact_cache_size_limit, actor, trigerring_actor, workflow, event_name, event, ref_name, ref_protected, ref_type, secret_source, workflow_ref, workflow_sha, workspace}' > github-context.json
              shell: bash

            - name: Commit built site to main branch
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "STATIC BUILD: ${{ github.event.head_commit.message || inputs.commitMessage }}"
                  commit_user_name: static-site-builder[bot]
                  commit_user_email: static-site-builder[bot]@users.noreply.github.com
                  tagging_message: prod
