name: Build static site

on:
    workflow_call:
        inputs:
            commitMessage:
                required: true
                type: string
        secrets:
            USERNAME:
                required: true
            MY_GITHUB_PAT:
                required: true
    workflow_dispatch:
        inputs:
            commitMessage:
                description: "Commit message for static site build"
                default: "Manual build trigger"
                required: true
                type: string

concurrency:
    group: "build-static-site"
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build static site
              run: npm run prod-build --if-present

            - name: Run test
              run: npm test --if-present

            - name: Commit built site to main branch
              run: |
                  export GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
                  github_repo_url=${{ github.server_url }}/${{ github.repository }}.git
                  github_repo_url_with_credentials="https://${{ secrets.USERNAME }}:${{ secrets.MY_GITHUB_PAT }}@${github_repo_url#https://}"

                  git config user.name static-site-builder[bot]
                  git config user.email static-site-builder[bot]@users.noreply.github.com

                  git remote add github "$github_repo_url_with_credentials"
                  git add --all
                  git status
                  git commit -m "STATIC BUILD: ${{ github.event.head_commit.message || inputs.commitMessage }}"

                  branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
                  git push github "$branch_name"
              shell: bash
