name: Full CI Pipeline

on:
    push:
        branches: "main"
        tags-ignore: "prod"
    workflow_dispatch:
        inputs:
            commitMessage:
                description: "Commit message for full CI pipeline"
                default: "Manual full CI pipeline trigger"
                required: true
                type: string

concurrency:
    group: "full-ci-pipeline"
    cancel-in-progress: true

jobs:
    pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Build static site
              uses: ./.github/workflows/build-static-site.yaml
              with:
                  commitMessage: ${{ github.event.head_commit.message || inputs.commitMessage }}

            - name: Sync Repo to GitLab
              uses: ./.github/workflows/sync-repo-to-gitlab.yaml
              with:
                  commitMessage: ${{ github.event.head_commit.message || inputs.commitMessage }}
              secrets: inherit
