name: Full CI Pipeline

on:
    push:
        branches: "main"
        tags-ignore: "prod"
    workflow_dispatch:
        inputs:
            commitMessage:
                description: "Commit message for full CI pipeline"
                default: "Manual full CI pipeline trigger"
                required: true
                type: string

concurrency:
    group: "full-ci-pipeline"
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    build_static_site:
        uses: ./.github/workflows/build-static-site.yaml
        with:
            commitMessage: ${{ github.event.head_commit.message || inputs.commitMessage }}

    sync_repo_to_gitlab:
        needs: build_static_site
        uses: ./.github/workflows/sync-repo-to-gitlab.yaml
        with:
            commitMessage: ${{ github.event.head_commit.message || inputs.commitMessage }}
        secrets: inherit
