name: Sync Repo to GitLab

on:
    workflow_dispatch:

    workflow_run:
        workflows: ["Build static site"]
        types:
            - completed

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Push to GitLab
              run: |
                  export GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
                  ls -R
              #   gitlab_repo_url=${{ secrets.GITLAB_URL }}
              #   gitlab_repo_url=${gitlab_repo_url#https://}
              #   gitlab_repo_url_with_credentials="https://${{ secrets.USERNAME }}:${{ secrets.GITLAB_PAT }}@${gitlab_repo_url}"
              #   git remote add gitlab "$gitlab_repo_url_with_credentials"
              #   branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
              #   git push gitlab "$branch_name"
              shell: bash
